[build]
target = "index.html"
dist = "dist"
filehash = false
public_url = "/key2words/"

[watch]
ignore = ["./src-tauri"]

[serve]
addresses = ["127.0.0.1"]
port = 1420
open = false
ws_protocol = "ws"

[tools]
# https://github.com/WebAssembly/binaryen/releases
wasm_opt = "version_125"
